// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC74swogJ-0KcS1j7cDvPYf_osimK5pi8c',
    appId: '1:910097320675:web:d8bae6e47a5f309b0f93d6',
    messagingSenderId: '910097320675',
    projectId: 'ai-financial-assistant-8f88e',
    authDomain: 'ai-financial-assistant-8f88e.firebaseapp.com',
    storageBucket: 'ai-financial-assistant-8f88e.firebasestorage.app',
    measurementId: 'G-5ZC0DTFEY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnevqNEmDSLSNyCX9SBnty97Irvo7BslE',
    appId: '1:910097320675:android:76bb95a6b03a171e0f93d6',
    messagingSenderId: '910097320675',
    projectId: 'ai-financial-assistant-8f88e',
    storageBucket: 'ai-financial-assistant-8f88e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNbcu77Tr8IqYM0zTog4mEsMw-N3f9ngI',
    appId: '1:910097320675:ios:1d7346a9567d95e60f93d6',
    messagingSenderId: '910097320675',
    projectId: 'ai-financial-assistant-8f88e',
    storageBucket: 'ai-financial-assistant-8f88e.firebasestorage.app',
    iosClientId: '910097320675-3d966s8eqgs3n65or0c33q2t9m995e7n.apps.googleusercontent.com',
    iosBundleId: 'com.example.genaiFinancialAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNbcu77Tr8IqYM0zTog4mEsMw-N3f9ngI',
    appId: '1:910097320675:ios:1d7346a9567d95e60f93d6',
    messagingSenderId: '910097320675',
    projectId: 'ai-financial-assistant-8f88e',
    storageBucket: 'ai-financial-assistant-8f88e.firebasestorage.app',
    iosClientId: '910097320675-3d966s8eqgs3n65or0c33q2t9m995e7n.apps.googleusercontent.com',
    iosBundleId: 'com.example.genaiFinancialAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC74swogJ-0KcS1j7cDvPYf_osimK5pi8c',
    appId: '1:910097320675:web:4c9d420d0079d01c0f93d6',
    messagingSenderId: '910097320675',
    projectId: 'ai-financial-assistant-8f88e',
    authDomain: 'ai-financial-assistant-8f88e.firebaseapp.com',
    storageBucket: 'ai-financial-assistant-8f88e.firebasestorage.app',
    measurementId: 'G-7HSYC6Z5SP',
  );

}